# Generated by Django 3.0.5 on 2020-05-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0002_auto_20200510_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeseason',
            name='no_of_episodes',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
